//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillar.UI.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UndoHistoryLimit {
            get {
                return ((int)(this["UndoHistoryLimit"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double DefaultModelZStandoffFromOrigin {
            get {
                return ((double)(this["DefaultModelZStandoffFromOrigin"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("126")]
        public double PrintableVolumeX {
            get {
                return ((double)(this["PrintableVolumeX"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("223")]
        public double PrintableVolumeY {
            get {
                return ((double)(this["PrintableVolumeY"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double PrintableVolumeZ {
            get {
                return ((double)(this["PrintableVolumeZ"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Coding\\Pillar\\SampleProjects\\Sample.gph")]
        public string LoadAtStartup {
            get {
                return ((string)(this["LoadAtStartup"]));
            }
            set {
                this["LoadAtStartup"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int SupportSides {
            get {
                return ((int)(this["SupportSides"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF00AEEF")]
        public string ScaledCursorCircleColor {
            get {
                return ((string)(this["ScaledCursorCircleColor"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFB3B3B3")]
        public string DefaultModelColor {
            get {
                return ((string)(this["DefaultModelColor"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CCFFD700")]
        public string FaceSetSelectionColor {
            get {
                return ((string)(this["FaceSetSelectionColor"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SupportPresetsJson {
            get {
                return ((string)(this["SupportPresetsJson"]));
            }
            set {
                this["SupportPresetsJson"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FaceAngleHighlightEnabled {
            get {
                return ((bool)(this["FaceAngleHighlightEnabled"]));
            }
            set {
                this["FaceAngleHighlightEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int FaceAngleThresholdDegrees {
            get {
                return ((int)(this["FaceAngleThresholdDegrees"]));
            }
            set {
                this["FaceAngleThresholdDegrees"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#fc037b")]
        public string FaceAngleHighlightColor {
            get {
                return ((string)(this["FaceAngleHighlightColor"]));
            }
            set {
                this["FaceAngleHighlightColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00ce19")]
        public string SelectionOutlineColor {
            get {
                return ((string)(this["SelectionOutlineColor"]));
            }
            set {
                this["SelectionOutlineColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ViewportRenderScale {
            get {
                return ((double)(this["ViewportRenderScale"]));
            }
            set {
                this["ViewportRenderScale"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ScaledCursorDiameter {
            get {
                return ((double)(this["ScaledCursorDiameter"]));
            }
            set {
                this["ScaledCursorDiameter"] = value;
            }
        }
    }
}
